# config/services.yaml
parameters:
    # Configuration JWT
    upload_dir: "%kernel.project_dir%/public/uploads"
    jwt.secret: '%env(JWT_SECRET)%'
    jwt.ttl: '%env(JWT_TTL)%'
    app.jwt.secret: '%env(string:JWT_SECRET)%'
    app.jwt.ttl: '%env(int:JWT_TTL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $jwtSecret: '%app.jwt.secret%'
            int $jwtTtl: '%app.jwt.ttl%'

    App\helpers\laravel_helper: ~
    # Déclaration ABSOLUMENT EXPLICITE
    App\Service\JwtService:
        arguments:
            $secret: '%jwt.secret%'
            $ttl: '%jwt.ttl%'
        autowire: false  # Important pour forcer l'utilisation des arguments

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'